
package javaapplication9;

import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class MainMenu extends javax.swing.JFrame {
    
    //Deklarasi variabel
    int Price_FriedChicken = 35000;
    int Price_Burger = 25000;
    int Price_Sandwich = 28000;
    int Price_FrenchFries = 20000;
    int Price_OnionRing = 23000;
    int Price_Pepsi = 15000;
    int Price_IcedTea = 17000;
    int Price_Coffee = 22000;
    int Price_OrangeJuice = 18000;
    int Price_MineralWater = 10000;
    
    int iTax, iTotal, iSubTotal, iPay;
    
    int[] itemcost = new int[10];//array
            
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jchkFriedChicken = new javax.swing.JCheckBox();
        jchkBurger = new javax.swing.JCheckBox();
        jchkSandwich = new javax.swing.JCheckBox();
        jchkFrenchFries = new javax.swing.JCheckBox();
        jchkOnionRing = new javax.swing.JCheckBox();
        jtxtFriedChicken = new javax.swing.JTextField();
        jtxtBurger = new javax.swing.JTextField();
        jtxtSandwich = new javax.swing.JTextField();
        jtxtFrenchFries = new javax.swing.JTextField();
        jtxtOnionRing = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jchkPepsi = new javax.swing.JCheckBox();
        jchkIcedTea = new javax.swing.JCheckBox();
        jchkCoffee = new javax.swing.JCheckBox();
        jchkOrangeJuice = new javax.swing.JCheckBox();
        jchkMineralWater = new javax.swing.JCheckBox();
        jtxtPepsi = new javax.swing.JTextField();
        jtxtIcedTea = new javax.swing.JTextField();
        jtxtCoffee = new javax.swing.JTextField();
        jtxtOrangeJuice = new javax.swing.JTextField();
        jtxtMineralWater = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcmbpaymethod = new javax.swing.JComboBox<>();
        jtxtPay = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtChange = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbuttonTotal = new javax.swing.JButton();
        jbuttonReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtArea = new javax.swing.JTextArea();
        jbuttonOrder = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jbuttonExit = new javax.swing.JButton();
        jbuttonChange = new javax.swing.JButton();
        jbuttonCetakPesanan = new javax.swing.JButton();
        jbuttonNewOrder = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 4));

        jLabel10.setFont(new java.awt.Font("Script MT Bold", 3, 48)); // NOI18N
        jLabel10.setText("Main Menu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(jLabel10)
                .addContainerGap(344, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, 933, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 4));

        jchkFriedChicken.setText("Fried Chiken");
        jchkFriedChicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkFriedChickenActionPerformed(evt);
            }
        });

        jchkBurger.setText("Burger");
        jchkBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkBurgerActionPerformed(evt);
            }
        });

        jchkSandwich.setText("Sandwich");
        jchkSandwich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkSandwichActionPerformed(evt);
            }
        });

        jchkFrenchFries.setText("French Fries");
        jchkFrenchFries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkFrenchFriesActionPerformed(evt);
            }
        });

        jchkOnionRing.setText("Onion Ring");
        jchkOnionRing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkOnionRingActionPerformed(evt);
            }
        });

        jtxtFriedChicken.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtFriedChicken.setText("0");
        jtxtFriedChicken.setEnabled(false);
        jtxtFriedChicken.setMinimumSize(new java.awt.Dimension(72, 22));
        jtxtFriedChicken.setPreferredSize(new java.awt.Dimension(72, 22));
        jtxtFriedChicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFriedChickenActionPerformed(evt);
            }
        });
        jtxtFriedChicken.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtFriedChickenKeyTyped(evt);
            }
        });

        jtxtBurger.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtBurger.setText("0");
        jtxtBurger.setEnabled(false);
        jtxtBurger.setPreferredSize(new java.awt.Dimension(72, 22));
        jtxtBurger.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtBurgerKeyTyped(evt);
            }
        });

        jtxtSandwich.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtSandwich.setText("0");
        jtxtSandwich.setEnabled(false);
        jtxtSandwich.setPreferredSize(new java.awt.Dimension(72, 22));
        jtxtSandwich.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtSandwichKeyTyped(evt);
            }
        });

        jtxtFrenchFries.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtFrenchFries.setText("0");
        jtxtFrenchFries.setEnabled(false);
        jtxtFrenchFries.setMinimumSize(new java.awt.Dimension(72, 22));
        jtxtFrenchFries.setPreferredSize(new java.awt.Dimension(72, 22));
        jtxtFrenchFries.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtFrenchFriesKeyTyped(evt);
            }
        });

        jtxtOnionRing.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtOnionRing.setText("0");
        jtxtOnionRing.setEnabled(false);
        jtxtOnionRing.setPreferredSize(new java.awt.Dimension(72, 22));
        jtxtOnionRing.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtOnionRingKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setText("Foods");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication9/rsz_1fc-removebg-preview.png"))); // NOI18N

        jLabel13.setText("Rp35.000,-");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication9/rsz_burger-removebg-preview.png"))); // NOI18N

        jLabel15.setText("Rp25.000,-");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication9/rsz_2sandwich-removebg-preview.png"))); // NOI18N

        jLabel17.setText("Rp28.000,-");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication9/rsz_french-fries-removebg-preview.png"))); // NOI18N

        jLabel19.setText("Rp20.000,-");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication9/rsz_onion-removebg-preview.png"))); // NOI18N

        jLabel21.setText("Rp23.000,-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jchkOnionRing)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel21)))
                        .addGap(18, 18, 18)
                        .addComponent(jtxtOnionRing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jchkFriedChicken)
                                            .addComponent(jchkBurger))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel13))
                                        .addGap(18, 18, 18))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jchkSandwich)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jLabel17)))))
                                .addGap(25, 25, 25)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtSandwich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtFriedChicken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jchkFrenchFries)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel19)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtFrenchFries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jtxtFriedChicken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jchkFriedChicken)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel13)
                            .addGap(12, 12, 12))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jchkBurger)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15))
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jchkSandwich)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jchkFrenchFries)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jtxtBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jtxtSandwich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jtxtFrenchFries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jchkOnionRing)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jtxtOnionRing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 124, -1, 592));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 4));

        jchkPepsi.setText("Pepsi");
        jchkPepsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkPepsiActionPerformed(evt);
            }
        });

        jchkIcedTea.setText("Iced Tea");
        jchkIcedTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkIcedTeaActionPerformed(evt);
            }
        });

        jchkCoffee.setText("Coffee");
        jchkCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkCoffeeActionPerformed(evt);
            }
        });

        jchkOrangeJuice.setText("Orange Juice");
        jchkOrangeJuice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkOrangeJuiceActionPerformed(evt);
            }
        });

        jchkMineralWater.setText("Mineral Water");
        jchkMineralWater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkMineralWaterActionPerformed(evt);
            }
        });

        jtxtPepsi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtPepsi.setText("0");
        jtxtPepsi.setEnabled(false);
        jtxtPepsi.setPreferredSize(new java.awt.Dimension(72, 22));
        jtxtPepsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPepsiActionPerformed(evt);
            }
        });
        jtxtPepsi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtPepsiKeyTyped(evt);
            }
        });

        jtxtIcedTea.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtIcedTea.setText("0");
        jtxtIcedTea.setEnabled(false);
        jtxtIcedTea.setMinimumSize(new java.awt.Dimension(72, 22));
        jtxtIcedTea.setPreferredSize(new java.awt.Dimension(72, 22));
        jtxtIcedTea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtIcedTeaKeyTyped(evt);
            }
        });

        jtxtCoffee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCoffee.setText("0");
        jtxtCoffee.setEnabled(false);
        jtxtCoffee.setPreferredSize(new java.awt.Dimension(72, 22));
        jtxtCoffee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCoffeeKeyTyped(evt);
            }
        });

        jtxtOrangeJuice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtOrangeJuice.setText("0");
        jtxtOrangeJuice.setEnabled(false);
        jtxtOrangeJuice.setPreferredSize(new java.awt.Dimension(72, 22));
        jtxtOrangeJuice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtOrangeJuiceKeyTyped(evt);
            }
        });

        jtxtMineralWater.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtMineralWater.setText("0");
        jtxtMineralWater.setEnabled(false);
        jtxtMineralWater.setPreferredSize(new java.awt.Dimension(72, 22));
        jtxtMineralWater.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtMineralWaterKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("Drinks");

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication9/rsz_1pepsi.png"))); // NOI18N

        jLabel22.setText("Rp15.000,-");

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication9/rsz_1iced_tea.png"))); // NOI18N

        jLabel25.setText("Rp17.000,-");

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication9/rsz_coffee.png"))); // NOI18N

        jLabel27.setText("Rp22.000,-");

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication9/rsz_2orange_juice.png"))); // NOI18N

        jLabel28.setText("Rp18.000,-");

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication9/rsz_mineral_water.png"))); // NOI18N

        jLabel31.setText("Rp10.000,-");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel30))
                                    .addComponent(jLabel29)))))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(jLabel23))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jchkIcedTea)
                                    .addComponent(jchkPepsi)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel25)
                                            .addComponent(jLabel22)))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel27))
                                    .addComponent(jchkCoffee))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(21, 21, 21)
                                            .addComponent(jLabel28))
                                        .addComponent(jchkOrangeJuice))
                                    .addGap(24, 24, 24))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jchkMineralWater)
                                    .addGap(18, 18, 18))))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtIcedTea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtPepsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtOrangeJuice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtMineralWater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel23))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jchkPepsi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel24))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jchkIcedTea)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel26))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jchkCoffee)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel27)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel29))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jchkOrangeJuice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel28)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel30))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jchkMineralWater)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel31))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jtxtPepsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(jtxtIcedTea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(jtxtCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jtxtOrangeJuice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(jtxtMineralWater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 124, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 4));

        jLabel1.setText("Payment Method");

        jcmbpaymethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Debit Card", "QRIS" }));
        jcmbpaymethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbpaymethodActionPerformed(evt);
            }
        });

        jtxtPay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtPay.setText("0");
        jtxtPay.setPreferredSize(new java.awt.Dimension(72, 22));

        jLabel2.setText("Pay");

        jtxtChange.setPreferredSize(new java.awt.Dimension(72, 22));

        jtxtTax.setPreferredSize(new java.awt.Dimension(72, 22));
        jtxtTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTaxActionPerformed(evt);
            }
        });

        jtxtSubTotal.setPreferredSize(new java.awt.Dimension(72, 22));
        jtxtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSubTotalActionPerformed(evt);
            }
        });

        jtxtTotal.setPreferredSize(new java.awt.Dimension(72, 22));
        jtxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalActionPerformed(evt);
            }
        });

        jLabel3.setText("Change");

        jLabel4.setText("Tax");

        jLabel5.setText("Subtotal");

        jLabel6.setText("Total");

        jbuttonTotal.setText("Total");
        jbuttonTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonTotalActionPerformed(evt);
            }
        });

        jbuttonReset.setText("Reset");
        jbuttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonResetActionPerformed(evt);
            }
        });

        jtxtArea.setColumns(20);
        jtxtArea.setRows(5);
        jScrollPane1.setViewportView(jtxtArea);

        jbuttonOrder.setText("Order");
        jbuttonOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonOrderActionPerformed(evt);
            }
        });

        jLabel7.setText("Data Pemesanan");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setText("Payment");

        jbuttonExit.setText("Exit");
        jbuttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonExitActionPerformed(evt);
            }
        });

        jbuttonChange.setText("Change");
        jbuttonChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonChangeActionPerformed(evt);
            }
        });

        jbuttonCetakPesanan.setText("Cetak Pesanan");
        jbuttonCetakPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonCetakPesananActionPerformed(evt);
            }
        });

        jbuttonNewOrder.setText("New Order");
        jbuttonNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonNewOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel1)
                            .addComponent(jcmbpaymethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbuttonReset)
                            .addComponent(jbuttonTotal))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jbuttonChange))
                                .addGap(73, 73, 73)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbuttonCetakPesanan)
                                    .addComponent(jLabel3)
                                    .addComponent(jtxtChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jbuttonOrder)
                            .addGap(18, 18, 18)
                            .addComponent(jbuttonNewOrder)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbuttonExit))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jbuttonTotal)
                        .addGap(16, 16, 16)
                        .addComponent(jbuttonReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcmbpaymethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbuttonChange)
                    .addComponent(jbuttonCetakPesanan))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbuttonOrder)
                    .addComponent(jbuttonExit)
                    .addComponent(jbuttonNewOrder))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 124, -1, 592));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    //Checkbox Onion Ring
    private void jchkOnionRingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkOnionRingActionPerformed
        // TODO add your handling code here:
        if (jchkOnionRing.isSelected()){
            jtxtOnionRing.setEnabled(true);
            jtxtOnionRing.requestFocus();
            jtxtOnionRing.setText("");
        }
        else{
            jtxtOnionRing.setEnabled(false);
            jtxtOnionRing.setText("0");
        }    
    }//GEN-LAST:event_jchkOnionRingActionPerformed

private JFrame frame;
    private void jbuttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonExitActionPerformed
        // TODO add your handling code here:
        // Kembali ke halaman login
        Login lg = new Login();
        lg.show();
        dispose();
        /*frame = new JFrame ("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Do you want to exit?", "zimS Fast Food", 
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }*/
    }//GEN-LAST:event_jbuttonExitActionPerformed

    private void jbuttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonResetActionPerformed
        // TODO add your handling code here:
        // textfield tiap menu bernilai 0 ketika klik reset button
        jtxtFriedChicken.setText("0");
        jtxtBurger.setText("0");
        jtxtSandwich.setText("0");
        jtxtFrenchFries.setText("0");
        jtxtOnionRing.setText("0");
        jtxtPepsi.setText("0");
        jtxtIcedTea.setText("0");
        jtxtCoffee.setText("0");
        jtxtOrangeJuice.setText("0");
        jtxtMineralWater.setText("0");
        jtxtPay.setText("0");
        
        // textfield tiap menu disable
        jtxtFriedChicken.setEnabled(false);
        jtxtBurger.setEnabled(false);
        jtxtSandwich.setEnabled(false);
        jtxtFrenchFries.setEnabled(false);
        jtxtOnionRing.setEnabled(false);
        jtxtPepsi.setEnabled(false);
        jtxtIcedTea.setEnabled(false);
        jtxtCoffee.setEnabled(false);
        jtxtOrangeJuice.setEnabled(false);
        jtxtMineralWater.setEnabled(false);
        
        // textfield di payment has no value
        jtxtTotal.setText(null);
        jtxtSubTotal.setText(null);
        jtxtTax.setText(null);
        jtxtChange.setText(null);
        
        //================================================
        
        // checkbox tiap menu unchecklist
        jchkFriedChicken.setSelected(false);
        jchkBurger.setSelected(false);
        jchkSandwich.setSelected(false);
        jchkFrenchFries.setSelected(false);
        jchkOnionRing.setSelected(false);
        jchkPepsi.setSelected(false);
        jchkIcedTea.setSelected(false);
        jchkCoffee.setSelected(false);
        jchkOrangeJuice.setSelected(false);
        jchkMineralWater.setSelected(false);
        
    }//GEN-LAST:event_jbuttonResetActionPerformed

    private void jchkFriedChickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkFriedChickenActionPerformed
        // TODO add your handling code here:
        if (jchkFriedChicken.isSelected()){ // jika checkbox suatu menu dichecklist maka
            jtxtFriedChicken.setEnabled(true); // textfield menu tersebut enable
            jtxtFriedChicken.requestFocus(); // cursor auto focus ke textfield tsb
            jtxtFriedChicken.setText(""); // textfield berisi kosong
        }
        else{ // jika tidak dichecklist
            jtxtFriedChicken.setEnabled(false); // textfield disable
            jtxtFriedChicken.setText("0"); // textfield bernilai 0
        }      
    }//GEN-LAST:event_jchkFriedChickenActionPerformed

    private void jtxtFriedChickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFriedChickenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFriedChickenActionPerformed

    //Textfield hanya bisa diisi oleh angka
    private void jtxtFriedChickenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtFriedChickenKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar(); // variabel iNumber: semua char dlm keyboard
        
        if (!(Character.isDigit(iNumber)) // jika character bukan digit maka
        ||(iNumber ==KeyEvent.VK_BACK_SPACE) // constant for the back_space virtual key
        ||(iNumber ==KeyEvent.VK_DELETE)){ // constant for the delete key
        evt.consume();
    }           
    }//GEN-LAST:event_jtxtFriedChickenKeyTyped

    private void jtxtBurgerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBurgerKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        ||(iNumber ==KeyEvent.VK_BACK_SPACE)
        ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }//GEN-LAST:event_jtxtBurgerKeyTyped
    }
    
    private void jtxtSandwichKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtSandwichKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        ||(iNumber ==KeyEvent.VK_BACK_SPACE)
        ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }//GEN-LAST:event_jtxtSandwichKeyTyped
    }
    
    private void jtxtFrenchFriesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtFrenchFriesKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        ||(iNumber ==KeyEvent.VK_BACK_SPACE)
        ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }//GEN-LAST:event_jtxtFrenchFriesKeyTyped
    }
    
    private void jtxtOnionRingKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtOnionRingKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        ||(iNumber ==KeyEvent.VK_BACK_SPACE)
        ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }//GEN-LAST:event_jtxtOnionRingKeyTyped
    }
        
    private void jtxtPepsiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPepsiKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        ||(iNumber ==KeyEvent.VK_BACK_SPACE)
        ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }//GEN-LAST:event_jtxtPepsiKeyTyped
    }
    
    private void jtxtIcedTeaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtIcedTeaKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        ||(iNumber ==KeyEvent.VK_BACK_SPACE)
        ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }//GEN-LAST:event_jtxtIcedTeaKeyTyped
    }
    
    private void jtxtCoffeeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCoffeeKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        ||(iNumber ==KeyEvent.VK_BACK_SPACE)
        ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }//GEN-LAST:event_jtxtCoffeeKeyTyped
    }
    
    private void jtxtOrangeJuiceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtOrangeJuiceKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        ||(iNumber ==KeyEvent.VK_BACK_SPACE)
        ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }//GEN-LAST:event_jtxtOrangeJuiceKeyTyped
    }
    
    private void jtxtMineralWaterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtMineralWaterKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        ||(iNumber ==KeyEvent.VK_BACK_SPACE)
        ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }//GEN-LAST:event_jtxtMineralWaterKeyTyped
    }
    
    private void jchkBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkBurgerActionPerformed
        // TODO add your handling code here:
        if (jchkBurger.isSelected()){
            jtxtBurger.setEnabled(true);
            jtxtBurger.requestFocus();
            jtxtBurger.setText("");
        }
        else{
            jtxtBurger.setEnabled(false);
            jtxtBurger.setText("0");
        }    
    }//GEN-LAST:event_jchkBurgerActionPerformed

    private void jchkSandwichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkSandwichActionPerformed
        // TODO add your handling code here:
        if (jchkSandwich.isSelected()){
            jtxtSandwich.setEnabled(true);
            jtxtSandwich.requestFocus();
            jtxtSandwich.setText("");
        }
        else{
            jtxtSandwich.setEnabled(false);
            jtxtSandwich.setText("0");
        }    
    }//GEN-LAST:event_jchkSandwichActionPerformed

    private void jchkFrenchFriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkFrenchFriesActionPerformed
        // TODO add your handling code here:
        if (jchkFrenchFries.isSelected()){
            jtxtFrenchFries.setEnabled(true);
            jtxtFrenchFries.requestFocus();
            jtxtFrenchFries.setText("");
        }
        else{
            jtxtFrenchFries.setEnabled(false);
            jtxtFrenchFries.setText("0");
        }    
    }//GEN-LAST:event_jchkFrenchFriesActionPerformed

    private void jchkPepsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkPepsiActionPerformed
        // TODO add your handling code here:
        if (jchkPepsi.isSelected()){
            jtxtPepsi.setEnabled(true);
            jtxtPepsi.requestFocus();
            jtxtPepsi.setText("");
        }
        else{
            jtxtPepsi.setEnabled(false);
            jtxtPepsi.setText("0");
        }    
    }//GEN-LAST:event_jchkPepsiActionPerformed

    private void jchkIcedTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkIcedTeaActionPerformed
        // TODO add your handling code here:
        if (jchkIcedTea.isSelected()){
            jtxtIcedTea.setEnabled(true);
            jtxtIcedTea.requestFocus();
            jtxtIcedTea.setText("");
        }
        else{
            jtxtIcedTea.setEnabled(false);
            jtxtIcedTea.setText("0");
        }    
    }//GEN-LAST:event_jchkIcedTeaActionPerformed

    private void jchkCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkCoffeeActionPerformed
        // TODO add your handling code here:
        if (jchkCoffee.isSelected()){
            jtxtCoffee.setEnabled(true);
            jtxtCoffee.requestFocus();
            jtxtCoffee.setText("");
        }
        else{
            jtxtCoffee.setEnabled(false);
            jtxtCoffee.setText("0");
        }    
    }//GEN-LAST:event_jchkCoffeeActionPerformed

    private void jchkOrangeJuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkOrangeJuiceActionPerformed
        // TODO add your handling code here:
        if (jchkOrangeJuice.isSelected()){
            jtxtOrangeJuice.setEnabled(true);
            jtxtOrangeJuice.requestFocus();
            jtxtOrangeJuice.setText("");
        }
        else{
            jtxtOrangeJuice.setEnabled(false);
            jtxtOrangeJuice.setText("0");
        }    
    }//GEN-LAST:event_jchkOrangeJuiceActionPerformed

    private void jchkMineralWaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkMineralWaterActionPerformed
        // TODO add your handling code here:
        if (jchkMineralWater.isSelected()){
            jtxtMineralWater.setEnabled(true);
            jtxtMineralWater.requestFocus();
            jtxtMineralWater.setText("");
        }
        else{
            jtxtMineralWater.setEnabled(false);
            jtxtMineralWater.setText("0");
        }    
    }//GEN-LAST:event_jchkMineralWaterActionPerformed
   
    private void jbuttonTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonTotalActionPerformed
        // TODO add your handling code here:
        // nilai pada textfield dimasukan pada tiap2 array
        itemcost[0] = Integer.parseInt(jtxtFriedChicken.getText());
        itemcost[1] = Integer.parseInt(jtxtBurger.getText());
        itemcost[2] = Integer.parseInt(jtxtSandwich.getText());
        itemcost[3] = Integer.parseInt(jtxtFrenchFries.getText());
        itemcost[4] = Integer.parseInt(jtxtOnionRing.getText());
        itemcost[5] = Integer.parseInt(jtxtPepsi.getText());
        itemcost[6] = Integer.parseInt(jtxtIcedTea.getText());
        itemcost[7] = Integer.parseInt(jtxtCoffee.getText());
        itemcost[8] = Integer.parseInt(jtxtOrangeJuice.getText());
        itemcost[9] = Integer.parseInt(jtxtMineralWater.getText());
        
        // menghitung sub total
        iSubTotal = Price_FriedChicken*itemcost [0] + Price_Burger*itemcost [1] 
                + Price_Sandwich*itemcost [2] + Price_FrenchFries*itemcost [3] 
                + Price_OnionRing*itemcost [4] + Price_Pepsi*itemcost [5] + Price_IcedTea*itemcost [6] 
                + Price_Coffee*itemcost [7] + Price_OrangeJuice*itemcost [8] 
                + Price_MineralWater*itemcost [9] ;
        
        // menghitung pajak
        iTax = (iSubTotal * 10)/100;
        
        // menghitung total keseluruhan
        iTotal = iSubTotal + iTax;
            
            // mengoutputkan nilai tiap-tiap perhitungan pada masing2 textfield
            String cTax = String.format("Rp%d", iTax);
            jtxtTax.setText(cTax);
        
            String cSubTotal = String.format("Rp%d", iSubTotal);
            jtxtSubTotal.setText(cSubTotal);
        
            String cTotal = String.format("Rp%d", iTotal);
            jtxtTotal.setText(cTotal);
    }//GEN-LAST:event_jbuttonTotalActionPerformed

    private void jtxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalActionPerformed

    private void jtxtTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTaxActionPerformed
    
    private void jbuttonChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonChangeActionPerformed
        // TODO add your handling code here:
        // variabel iPay berisi nilai pada textfield pay
        iPay = Integer.parseInt(jtxtPay.getText()); 
        // variabel string berisi item yang kita pilih
        String PaymentMethod = (String)jcmbpaymethod.getSelectedItem();
        
        if (PaymentMethod == "Cash"){// jika memilih cash maka
            if (iPay >= iTotal){ // dan jika nilai iPay >= iTotal maka
                // mengoutputkan iPay - iTotal pada textfield change
                String cChange = String.format("Rp%d", iPay - iTotal);
                jtxtChange.setText(cChange);
            } // jika nilai iPay kurang maka
            else {
                // menampilkan message dialog "not enough cash"
                JOptionPane.showMessageDialog(null, "Not enough cash entered", 
                        "zimS Fast Food", JOptionPane.OK_OPTION);
            }
        }
        
        //jika memilih lainnya (debit card and qris) maka
        else {
            // hanya mengoutputkan iPay - iTotal pada textfield change
            String cChange = String.format("Rp%d", iPay - iTotal);
            jtxtChange.setText(cChange);
        }
    }//GEN-LAST:event_jbuttonChangeActionPerformed
    
    private void jbuttonOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonOrderActionPerformed
        // TODO add your handling code here:
        String PaymentMethod = (String)jcmbpaymethod.getSelectedItem();
        
        //jika kita klik tombol order dan memilih cash, maka pesan yg ditampilkan
        if (PaymentMethod == "Cash"){
            JOptionPane.showMessageDialog(null, "Terima kasih Atas Pesanan Anda"+ "\n"
                    +"Pesanan Anda Akan Kami Proses");
        }
        
        //jika kita klik tombol order dan memilih debit card, maka pesan yg ditampilkan
        else if (PaymentMethod == "Debit Card"){
            JOptionPane.showMessageDialog(null, "Enter your debit card, please");
            JOptionPane.showMessageDialog(null, "Terima kasih Atas Pesanan Anda"+"\n"
                    +"Pesanan Anda Akan Kami Proses");
        }
        
        //jika kita klik tombol order dan memilih qris, maka pesan yg ditampilkan
        else {
            JOptionPane.showMessageDialog(null, "Scan the barcode, please");
            JOptionPane.showMessageDialog(null, "Terima kasih Atas Pesanan Anda"+"\n"
                    +"Pesanan Anda Akan Kami Proses");
        }
        
    }//GEN-LAST:event_jbuttonOrderActionPerformed
    
    private void jbuttonCetakPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonCetakPesananActionPerformed
        // TODO add your handling code here:
        String foods, drinks;
        
        //Foods
        StringBuffer var = new StringBuffer ();
        if (jchkFriedChicken.isSelected()) { // jika checkbox dichecklist, maka
            // menambahkan text pada checkbox dan nilai pada textfield ke dalam var
            var.append("\n");
            var.append(jchkFriedChicken.getText());
            var.append("\t");
            var.append(jtxtFriedChicken.getText());
        }  
        if (jchkBurger.isSelected()) {
            var.append("\n");
            var.append(jchkBurger.getText());
            var.append("\t");
            var.append(jtxtBurger.getText());
        }  
        if (jchkSandwich.isSelected()) {
            var.append("\n");
            var.append(jchkSandwich.getText());
            var.append("\t");
            var.append(jtxtSandwich.getText());
        }  
        if (jchkFrenchFries.isSelected()) {
            var.append("\n");
            var.append(jchkFrenchFries.getText());
            var.append("\t");
            var.append(jtxtFrenchFries.getText());
        }  
        if (jchkOnionRing.isSelected()) {
            var.append("\n");
            var.append(jchkOnionRing.getText());
            var.append("\t");
            var.append(jtxtOnionRing.getText());
        }
        // lalu program di atas disimpan pada variabel baru utk memudahkan pemanggilan
        foods = var.toString();
        
        //Drinks
        StringBuffer dri = new StringBuffer ();
        if (jchkPepsi.isSelected()) {
            dri.append("\n");
            dri.append(jchkPepsi.getText());
            dri.append("\t");
            dri.append(jtxtPepsi.getText());
        }  
        if (jchkIcedTea.isSelected()) {
            dri.append("\n");
            dri.append(jchkIcedTea.getText());
            dri.append("\t");
            dri.append(jtxtIcedTea.getText());
        }  
        if (jchkCoffee.isSelected()) {
            dri.append("\n");
            dri.append(jchkCoffee.getText());
            dri.append("\t");
            dri.append(jtxtCoffee.getText());
        }  
        if (jchkOrangeJuice.isSelected()) {
            dri.append("\n");
            dri.append(jchkOrangeJuice.getText());
            dri.append("\t");
            dri.append(jtxtOrangeJuice.getText());
        }  
        if (jchkMineralWater.isSelected()) {
            dri.append("\n");
            dri.append(jchkMineralWater.getText());
            dri.append("\t");
            dri.append(jtxtMineralWater.getText());
        }  
        drinks = dri.toString();
        
        // mengoutputkan pada textarea
        jtxtArea.setText(
        "Foods\t: " +foods+ "\n"+
        "\nDrinks\t: " +drinks+ "\n"+
        "\nSub Total\t: "+jtxtSubTotal.getText()+"\n"+
        "Tax\t: "+jtxtTax.getText()+"\n"+
        "Total\t: "+jtxtTotal.getText()+"\n"+
        "Pay\t: Rp"+jtxtPay.getText()+"\n"+
        "Change\t: "+jtxtChange.getText()+"\n");
    }//GEN-LAST:event_jbuttonCetakPesananActionPerformed

    private void jtxtPepsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPepsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPepsiActionPerformed

    private void jtxtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSubTotalActionPerformed
    
    // button new order -mike
    private void jbuttonNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonNewOrderActionPerformed
        // TODO add your handling code here:
        jtxtFriedChicken.setText("0");
        jtxtBurger.setText("0");
        jtxtSandwich.setText("0");
        jtxtFrenchFries.setText("0");
        jtxtOnionRing.setText("0");
        jtxtPepsi.setText("0");
        jtxtIcedTea.setText("0");
        jtxtCoffee.setText("0");
        jtxtOrangeJuice.setText("0");
        jtxtMineralWater.setText("0");
        jtxtPay.setText("0");
        
        jtxtFriedChicken.setEnabled(false);
        jtxtBurger.setEnabled(false);
        jtxtSandwich.setEnabled(false);
        jtxtFrenchFries.setEnabled(false);
        jtxtOnionRing.setEnabled(false);
        jtxtPepsi.setEnabled(false);
        jtxtIcedTea.setEnabled(false);
        jtxtCoffee.setEnabled(false);
        jtxtOrangeJuice.setEnabled(false);
        jtxtMineralWater.setEnabled(false);
        
        jtxtTotal.setText(null);
        jtxtSubTotal.setText(null);
        jtxtTax.setText(null);
        jtxtChange.setText(null);
        
        jtxtArea.setText("");//mengosongkan text area
        
        //================================================
        
        jchkFriedChicken.setSelected(false);
        jchkBurger.setSelected(false);
        jchkSandwich.setSelected(false);
        jchkFrenchFries.setSelected(false);
        jchkOnionRing.setSelected(false);
        jchkPepsi.setSelected(false);
        jchkIcedTea.setSelected(false);
        jchkCoffee.setSelected(false);
        jchkOrangeJuice.setSelected(false);
        jchkMineralWater.setSelected(false);
    }//GEN-LAST:event_jbuttonNewOrderActionPerformed

    private void jcmbpaymethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbpaymethodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbpaymethodActionPerformed
    
    /**
     * @param args the command line arguments
     */
    
    // run MainMenu
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbuttonCetakPesanan;
    private javax.swing.JButton jbuttonChange;
    private javax.swing.JButton jbuttonExit;
    private javax.swing.JButton jbuttonNewOrder;
    private javax.swing.JButton jbuttonOrder;
    private javax.swing.JButton jbuttonReset;
    private javax.swing.JButton jbuttonTotal;
    private javax.swing.JCheckBox jchkBurger;
    private javax.swing.JCheckBox jchkCoffee;
    private javax.swing.JCheckBox jchkFrenchFries;
    private javax.swing.JCheckBox jchkFriedChicken;
    private javax.swing.JCheckBox jchkIcedTea;
    private javax.swing.JCheckBox jchkMineralWater;
    private javax.swing.JCheckBox jchkOnionRing;
    private javax.swing.JCheckBox jchkOrangeJuice;
    private javax.swing.JCheckBox jchkPepsi;
    private javax.swing.JCheckBox jchkSandwich;
    private javax.swing.JComboBox<String> jcmbpaymethod;
    private javax.swing.JTextArea jtxtArea;
    private javax.swing.JTextField jtxtBurger;
    private javax.swing.JTextField jtxtChange;
    private javax.swing.JTextField jtxtCoffee;
    private javax.swing.JTextField jtxtFrenchFries;
    private javax.swing.JTextField jtxtFriedChicken;
    private javax.swing.JTextField jtxtIcedTea;
    private javax.swing.JTextField jtxtMineralWater;
    private javax.swing.JTextField jtxtOnionRing;
    private javax.swing.JTextField jtxtOrangeJuice;
    private javax.swing.JTextField jtxtPay;
    private javax.swing.JTextField jtxtPepsi;
    private javax.swing.JTextField jtxtSandwich;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
